#pragma once
#include <usb_keyboard.h>
#include "scancodes.h"

const int KEYMAP[] = {
    [SC_A] = KEY_A              ,
    [SC_B] = KEY_B              , 
    [SC_C] = KEY_C              ,
    [SC_D] = KEY_D              ,
    [SC_E] = KEY_E              ,
    [SC_F] = KEY_F              ,
    [SC_G] = KEY_G              ,
    [SC_H] = KEY_H              ,
    [SC_I] = KEY_I              ,
    [SC_J] = KEY_J              ,
    [SC_K] = KEY_K              ,
    [SC_L] = KEY_L              ,
    [SC_M] = KEY_M              ,
    [SC_N] = KEY_N              ,
    [SC_O] = KEY_O              ,
    [SC_P] = KEY_P              ,
    [SC_Q] = KEY_Q              ,
    [SC_R] = KEY_R              ,
    [SC_S] = KEY_S              ,
    [SC_T] = KEY_T              ,
    [SC_U] = KEY_U              ,
    [SC_V] = KEY_V              ,
    [SC_W] = KEY_W              ,
    [SC_X] = KEY_X              ,
    [SC_Y] = KEY_Y              ,
    [SC_Z] = KEY_Z              ,

    [SC_1] = KEY_1              ,
    [SC_2] = KEY_2              ,
    [SC_3] = KEY_3              ,
    [SC_4] = KEY_4              ,
    [SC_5] = KEY_5              ,
    [SC_6] = KEY_6              ,
    [SC_7] = KEY_7              ,
    [SC_8] = KEY_8              ,
    [SC_9] = KEY_9              ,
    [SC_0] = KEY_0              ,

    [SC_ENTER]     = KEY_ENTER  ,
    [SC_ESC]       = KEY_ESC    ,
    [SC_BACKSPACE] = KEY_BACKSPACE,
    [SC_TAB]       = KEY_TAB    ,
    [SC_SPACE]     = KEY_SPACE  ,
    [SC_MINUS]     = KEY_MINUS  ,
    [SC_EQUAL]     = KEY_EQUAL  , 
    [SC_LEFT_BRACE]  = KEY_LEFT_BRACE   ,
    [SC_RIGHT_BRACE] = KEY_RIGHT_BRACE  , 
    [SC_BACKSLASH]   = KEY_BACKSLASH    ,
    [SC_SEMICOLON] = KEY_SEMICOLON      ,
    [SC_QUOTE]     = KEY_QUOTE  ,
    [SC_TILDE]     = KEY_TILDE  ,
    [SC_COMMA]     = KEY_COMMA  ,
    [SC_PERIOD]    = KEY_PERIOD ,
    [SC_SLASH]     = KEY_SLASH  ,

    [SC_F1]  = KEY_F1,
    [SC_F2]  = KEY_F2,
    [SC_F3]  = KEY_F3,
    [SC_F4]  = KEY_F4,
    [SC_F5]  = KEY_F5,
    [SC_F6]  = KEY_F6,
    [SC_F7]  = KEY_F7,
    [SC_F8]  = KEY_F8,
    [SC_F9]  = KEY_F9,
    [SC_F10] = KEY_F10,

    [SC_NUMLOCK]    = KEY_NUM_LOCK,
    [SC_SCROLLLOCK] = KEYPAD_ASTERIX,

    [SC_KP_1] = KEYPAD_1,
    [SC_KP_2] = KEYPAD_2,
    [SC_KP_3] = KEYPAD_3,
    [SC_KP_4] = KEYPAD_4,
    [SC_KP_5] = KEYPAD_5,
    [SC_KP_6] = KEYPAD_6,
    [SC_KP_7] = KEYPAD_7,
    [SC_KP_8] = KEYPAD_8,
    [SC_KP_9] = KEYPAD_9,
    [SC_KP_0] = KEYPAD_0,

    [SC_KP_PERIOD] = KEYPAD_PERIOD,
    [SC_KP_PLUS] = KEYPAD_PLUS,
    [SC_KP_MINUS] = KEYPAD_MINUS,
    [SC_KP_STAR] = KEY_PRINTSCREEN,

    [MAX_SCANCODE_VALUE]  = 0                  
};
